"""Replacement receipt PDF."""
from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A5
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

BRAND = colors.HexColor("#0f766e")
LIGHT = colors.HexColor("#e6f2f0")


def _rs(v: float) -> str:
    return f"Rs.{(v or 0):,.2f}"


def build_receipt(r: dict) -> bytes:
    base = getSampleStyleSheet()
    brand = ParagraphStyle("b", parent=base["Title"], textColor=BRAND, fontSize=17, spaceAfter=2)
    sub = ParagraphStyle("s", parent=base["Normal"], fontSize=11, textColor=colors.HexColor("#444"))
    small = ParagraphStyle("sm", parent=base["Normal"], fontSize=8.5, textColor=colors.HexColor("#666"))
    sec = ParagraphStyle("sec", parent=base["Heading2"], fontSize=11, textColor=BRAND,
                         spaceBefore=10, spaceAfter=4)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A5, topMargin=13 * mm, bottomMargin=13 * mm,
                            leftMargin=13 * mm, rightMargin=13 * mm,
                            title=r["replacement_number"])
    story = [
        Paragraph("RESVI ENTERPRISES", brand),
        Paragraph("Replacement / Exchange Receipt", sub),
        Paragraph(
            f"{r['replacement_number']} &nbsp;|&nbsp; {r['date']} {r['time']}", small
        ),
        Spacer(1, 6),
    ]

    if r.get("customer_name") or r.get("mobile") or r.get("reason"):
        rows = []
        if r.get("customer_name"):
            rows.append(["Customer", r["customer_name"]])
        if r.get("mobile"):
            rows.append(["Mobile", r["mobile"]])
        if r.get("reason"):
            rows.append(["Reason", r["reason"]])
        t = Table(rows, colWidths=[32 * mm, 90 * mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), LIGHT),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d0d8d6")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t)

    story.append(Paragraph("Items", sec))
    rows = [["", "Product", "Qty", "Amount"]]
    rows.append(["Returned", r["returned_name"], str(r["returned_qty"]), _rs(r["old_amount"])])
    if r.get("replacement_name"):
        rows.append(["Replacement", r["replacement_name"], str(r["replacement_qty"]),
                     _rs(r["new_amount"])])
    else:
        rows.append(["Replacement", "\u2014 none (refund only) \u2014", "-", _rs(0)])
    t = Table(rows, colWidths=[26 * mm, 58 * mm, 14 * mm, 24 * mm], repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d0d8d6")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)

    story.append(Paragraph("Settlement", sec))
    srows = [["Old value", _rs(r["old_amount"])], ["New value", _rs(r["new_amount"])]]
    diff = r["difference"]
    srows.append(["Difference", ("+" if diff > 0 else "") + _rs(diff)])
    if r["collected_amount"] > 0:
        srows.append(["Customer paid", _rs(r["collected_amount"])])
        srows.append(["Payment method", (r.get("payment_method") or "").upper()])
    elif r["refund_amount"] > 0:
        srows.append(["Refunded to customer", _rs(r["refund_amount"])])
        srows.append(["Paid from", "CASH DRAWER"])
    else:
        srows.append(["Settlement", "Even exchange \u2014 nothing to pay"])
    t = Table(srows, colWidths=[60 * mm, 62 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), LIGHT),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (1, -1), (1, -1), BRAND),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d0d8d6")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)

    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by RESVI Billing App", small))
    doc.build(story)
    buf.seek(0)
    return buf.getvalue()
